### ISSUE TITLE
add support and example for other ant-design related libraries.

### ISSUE THREAD

**Issue by ye-will** [ye-will/next-plugin-antd#7]
- ant-motion
    - [ ] support
    - [ ] example
- ant-design-charts
    - [ ] support
    - [ ] example
- ant-design-pro-layout
    - [ ] support
    - [ ] example

Other libs are welcome too.

**Comment by rps-v** [comment]
`@ant-design/pro-table` does not work. Any ideas how to fix it ?

`yarn add @ant-design/pro-table`

```jsx
import ProTable from '@ant-design/pro-table'

export default function MyTable () {
  return <ProTable />
}
```

```
D:\test\node_modules\antd\es\config-provider\style\index.js:1
import './index.less';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\test\node_modules\@ant-design\pro-provider\lib\index.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```
